// Code generated by configgen.go; EDIT AT YOUR OWN RISK.
//go:build testcases
// +build testcases

package t7

import (
	"errors"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	TESTCONFIGDEFAULTS_REQUIRED_ENV = "TESTCONFIGDEFAULTS_REQUIRED"
	TESTCONFIGDEFAULTS_STR_ENV      = "TESTCONFIGDEFAULTS_STR"
	TESTCONFIGDEFAULTS_B_ENV        = "TESTCONFIGDEFAULTS_B"
	TESTCONFIGDEFAULTS_I_ENV        = "TESTCONFIGDEFAULTS_I"
	TESTCONFIGDEFAULTS_I8_ENV       = "TESTCONFIGDEFAULTS_I8"
	TESTCONFIGDEFAULTS_I16_ENV      = "TESTCONFIGDEFAULTS_I16"
	TESTCONFIGDEFAULTS_I32_ENV      = "TESTCONFIGDEFAULTS_I32"
	TESTCONFIGDEFAULTS_I64_ENV      = "TESTCONFIGDEFAULTS_I64"
	TESTCONFIGDEFAULTS_U_ENV        = "TESTCONFIGDEFAULTS_U"
	TESTCONFIGDEFAULTS_U8_ENV       = "TESTCONFIGDEFAULTS_U8"
	TESTCONFIGDEFAULTS_U16_ENV      = "TESTCONFIGDEFAULTS_U16"
	TESTCONFIGDEFAULTS_U32_ENV      = "TESTCONFIGDEFAULTS_U32"
	TESTCONFIGDEFAULTS_U64_ENV      = "TESTCONFIGDEFAULTS_U64"
	TESTCONFIGDEFAULTS_F32_ENV      = "TESTCONFIGDEFAULTS_F32"
	TESTCONFIGDEFAULTS_F64_ENV      = "TESTCONFIGDEFAULTS_F64"
	TESTCONFIGDEFAULTS_D_ENV        = "TESTCONFIGDEFAULTS_D"
)

var (
	ErrTestconfigdefaultsRequiredEnvMissing = errors.New(TESTCONFIGDEFAULTS_REQUIRED_ENV)
	ErrTestconfigdefaultsBEnvInvalid        = errors.New(TESTCONFIGDEFAULTS_B_ENV)
	ErrTestconfigdefaultsIEnvInvalid        = errors.New(TESTCONFIGDEFAULTS_I_ENV)
	ErrTestconfigdefaultsI8EnvInvalid       = errors.New(TESTCONFIGDEFAULTS_I8_ENV)
	ErrTestconfigdefaultsI16EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_I16_ENV)
	ErrTestconfigdefaultsI32EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_I32_ENV)
	ErrTestconfigdefaultsI64EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_I64_ENV)
	ErrTestconfigdefaultsUEnvInvalid        = errors.New(TESTCONFIGDEFAULTS_U_ENV)
	ErrTestconfigdefaultsU8EnvInvalid       = errors.New(TESTCONFIGDEFAULTS_U8_ENV)
	ErrTestconfigdefaultsU16EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_U16_ENV)
	ErrTestconfigdefaultsU32EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_U32_ENV)
	ErrTestconfigdefaultsU64EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_U64_ENV)
	ErrTestconfigdefaultsF32EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_F32_ENV)
	ErrTestconfigdefaultsF64EnvInvalid      = errors.New(TESTCONFIGDEFAULTS_F64_ENV)
	ErrTestconfigdefaultsDEnvInvalid        = errors.New(TESTCONFIGDEFAULTS_D_ENV)
)

func LoadTestConfigDefaults() (TestConfigDefaults, error) {
	var config TestConfigDefaults
	var missingVars []error
	var formatVars []error
	val_Required, ok := os.LookupEnv(TESTCONFIGDEFAULTS_REQUIRED_ENV)
	if !ok {
		missingVars = append(missingVars, ErrTestconfigdefaultsRequiredEnvMissing)
	} else {
		config.Required = val_Required
	}
	val_Str, ok := os.LookupEnv(TESTCONFIGDEFAULTS_STR_ENV)
	if !ok {
		val_Str = "hello"
		ok = true
	}
	if ok {
		config.Str = val_Str
	}
	val_B, ok := os.LookupEnv(TESTCONFIGDEFAULTS_B_ENV)
	if !ok {
		val_B = "true"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseBool(val_B)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsBEnvInvalid)
		} else {
			config.B = parsed
		}
	}
	val_I, ok := os.LookupEnv(TESTCONFIGDEFAULTS_I_ENV)
	if !ok {
		val_I = "-5"
		ok = true
	}
	if ok {
		parsed, err := strconv.Atoi(val_I)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsIEnvInvalid)
		} else {
			config.I = parsed
		}
	}
	val_I8, ok := os.LookupEnv(TESTCONFIGDEFAULTS_I8_ENV)
	if !ok {
		val_I8 = "-1"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseInt(val_I8, 10, 8)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsI8EnvInvalid)
		} else {
			config.I8 = int8(parsed)
		}
	}
	val_I16, ok := os.LookupEnv(TESTCONFIGDEFAULTS_I16_ENV)
	if !ok {
		val_I16 = "16"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseInt(val_I16, 10, 16)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsI16EnvInvalid)
		} else {
			config.I16 = int16(parsed)
		}
	}
	val_I32, ok := os.LookupEnv(TESTCONFIGDEFAULTS_I32_ENV)
	if !ok {
		val_I32 = "32"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseInt(val_I32, 10, 32)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsI32EnvInvalid)
		} else {
			config.I32 = int32(parsed)
		}
	}
	val_I64, ok := os.LookupEnv(TESTCONFIGDEFAULTS_I64_ENV)
	if !ok {
		val_I64 = "64"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseInt(val_I64, 10, 64)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsI64EnvInvalid)
		} else {
			config.I64 = int64(parsed)
		}
	}
	val_U, ok := os.LookupEnv(TESTCONFIGDEFAULTS_U_ENV)
	if !ok {
		val_U = "5"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseUint(val_U, 10, 0)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsUEnvInvalid)
		} else {
			config.U = uint(parsed)
		}
	}
	val_U8, ok := os.LookupEnv(TESTCONFIGDEFAULTS_U8_ENV)
	if !ok {
		val_U8 = "1"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseUint(val_U8, 10, 8)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsU8EnvInvalid)
		} else {
			config.U8 = uint8(parsed)
		}
	}
	val_U16, ok := os.LookupEnv(TESTCONFIGDEFAULTS_U16_ENV)
	if !ok {
		val_U16 = "16"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseUint(val_U16, 10, 16)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsU16EnvInvalid)
		} else {
			config.U16 = uint16(parsed)
		}
	}
	val_U32, ok := os.LookupEnv(TESTCONFIGDEFAULTS_U32_ENV)
	if !ok {
		val_U32 = "32"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseUint(val_U32, 10, 32)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsU32EnvInvalid)
		} else {
			config.U32 = uint32(parsed)
		}
	}
	val_U64, ok := os.LookupEnv(TESTCONFIGDEFAULTS_U64_ENV)
	if !ok {
		val_U64 = "64"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseUint(val_U64, 10, 64)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsU64EnvInvalid)
		} else {
			config.U64 = uint64(parsed)
		}
	}
	val_F32, ok := os.LookupEnv(TESTCONFIGDEFAULTS_F32_ENV)
	if !ok {
		val_F32 = "1.5"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseFloat(val_F32, 32)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsF32EnvInvalid)
		} else {
			config.F32 = float32(parsed)
		}
	}
	val_F64, ok := os.LookupEnv(TESTCONFIGDEFAULTS_F64_ENV)
	if !ok {
		val_F64 = "2.5"
		ok = true
	}
	if ok {
		parsed, err := strconv.ParseFloat(val_F64, 64)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsF64EnvInvalid)
		} else {
			config.F64 = parsed
		}
	}
	val_D, ok := os.LookupEnv(TESTCONFIGDEFAULTS_D_ENV)
	if !ok {
		val_D = "1500ms"
		ok = true
	}
	if ok {
		parsed, err := time.ParseDuration(val_D)
		if err != nil {
			formatVars = append(formatVars, ErrTestconfigdefaultsDEnvInvalid)
		} else {
			config.D = parsed
		}
	}

	if len(missingVars) > 0 || len(formatVars) > 0 {
		var verr error
		if len(missingVars) > 0 {
			verr = errors.Join(verr, MissingEnvVarsError{vars: missingVars})
		}
		if len(formatVars) > 0 {
			verr = errors.Join(verr, InvalidEnvVarsError{vars: formatVars})
		}
		return TestConfigDefaults{}, verr
	}

	return config, nil
}

type MissingEnvVarsError struct {
	vars []error
}

func (m MissingEnvVarsError) Unwrap() []error {
	return m.vars
}

func (m MissingEnvVarsError) Error() string {
	if len(m.vars) == 0 {
		return ""
	}
	varsstr := make([]string, 0, len(m.vars))
	for _, v := range m.vars {
		varsstr = append(varsstr, v.Error())
	}
	return "envs " + strings.Join(varsstr, ",") + " are not set"
}

type InvalidEnvVarsError struct {
	vars []error
}

func (m InvalidEnvVarsError) Unwrap() []error {
	return m.vars
}

func (m InvalidEnvVarsError) Error() string {
	if len(m.vars) == 0 {
		return ""
	}
	varsstr := make([]string, 0, len(m.vars))
	for _, v := range m.vars {
		varsstr = append(varsstr, v.Error())
	}
	return "envs " + strings.Join(varsstr, ",") + " have an invalid value"
}
